# Site settings
title: Bijaya Pandey
description: 'I love music and Technology.'
url: 'https://bijayapandey.com.np'
baseurl: ''
google_analytics: 'UA-100719136-1'
disqus_shortname: 'bijayapandey'
future: true

author:
  name: 'Bijay Pandey'
  email: creatorbzay1111@gmail.com
  twitter_username: BijayaPandey11
  facebook_username: BijayaPandey1111
  github_username:  bjpandey
  linkedin_username:  bijayapandey1111

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
